[workspace]
members = [
    "blank_lines_between_variants_or_fields",
    "import_grouping_and_ordering",
    "manual_type_annotations_in_let_statements",
    "nested_path_in_use_group",
    "pub_field_in_struct",
    "sorted_enum_variants",
    "thiserror_conventions",
    "to_string_on_string_types",
    "unnecessary_qualified_type_paths",
]
resolver = "3"

[workspace.metadata.dylint]
libraries = [
    { path = "blank_lines_between_variants_or_fields" },
    { path = "import_grouping_and_ordering" },
    { path = "manual_type_annotations_in_let_statements" },
    { path = "nested_path_in_use_group" },
    { path = "pub_field_in_struct" },
    { path = "sorted_enum_variants" },
    { path = "thiserror_conventions" },
    { path = "to_string_on_string_types" },
    { path = "unnecessary_qualified_type_paths" },
]
