[package]
name = "manual_type_annotations_in_let_statements"
version = "0.1.0"
authors = ["Sam L. Thomas <s@ghost.sh>"]
description = "Lint to detect manual type annotations in let statements"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "5.0"

[dev-dependencies]
dylint_testing = "5.0"

[package.metadata.rust-analyzer]
rustc_private = true
